<UserProfileView>:
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 30
        AsyncImage:
            source: "https://i.kym-cdn.com/entries/icons/original/000/013/564/doge.jpg"
        MDLabel:
            text: "Name Surname"
            font_style: "Title"
            halign: 'center'
        MDLabel:
            text: "0706123123"
            halign: 'center'
        MDLabel:
            text: "asdf@example.com"
            halign: 'center'
