dist: xenial

language: python

python: "3.7"

stages:
  - name: tests
    if: type == pull_request OR branch IN (master, dev)

jobs:
  include:
    - stage: tests
      name: "YAPF"
      script: bash ci/run_yapf.sh
    - script: bash ci/run_prospector.sh
      name: "Prospector"
    - script: bash ci/run_nose.sh
      name: "Unit tests"

script: ignore

notifications:
  email: false
  slack:
    rooms:
      - secure: JmU0DEkRTL0yqu1jJtyZc0LIWHM+U6eq6r907iKDYfNJQ2vDY95TmdW+lWHeFixMo6DkMaWgX1XST8qqDZp3lLNButgvYAMwfbKDj29wMVyBOG8ji/sZI8hoTHqxfnKxnLwkXvLCPHMF8T++reglCd/0d3130xRfraod3H1i532M6QvnCsLZJbyy/4V20arkz38oRvXLPaGMFSbUAktBOM5bthAT7iYh0AXgD9PO11ShsAATGjxGUqPvC8yrF6DQdODbH7sVwJskFT631lxC6Mn82Nx9TnqEQPvuF7zafClC87PTHvzHtre+GsSa1OfdRolXJXEEh0nhhtvNpnlKaYOL8+IdRVYIELyglatinhjg9vxnAYqLSWsxXX3Wg6Osbmhqvdc1xpioc/o02W9Er+NjdmDUWeA4XUSJv6XTUFtLS7cs9V0r+B+DRte5sAinTxiHJNYe/9/fBlzJY78tXoC3L3DLy3EHuZLH69KyS+B38W3zSENy3P8p/4b536TX7DB7E8U4YZr6uzVFwfPbJLu8DHw+BwyT0zQuXlFMhaQ0hrlBSSehLWPsEIwQA/oAEWwlXCWHp3NcEXNhqEAJ24Y9Kx66ThyfXJaNuj4tWzonNw6WNs166l0zeW5wmHJuTUT1O7sRM/H7GsQZPccVj7RsukNBqWaxjyPWvAgKAQY=
    on_success: never
    on_failure: always

